// @ts-check

/**
 * Curated animal list for generated pseudonyms (§11.6 "`animal` from a
 * curated list (~60 animals, no offensive or ambiguous words)"). Kept as
 * a flat, alphabetically-unsorted constant — reordering/adding entries
 * changes which names exist, so review any change here like a content
 * change, not a refactor.
 */
export const ANIMALS = Object.freeze([
  'Fox',
  'Owl',
  'Wolf',
  'Otter',
  'Falcon',
  'Panda',
  'Tiger',
  'Lion',
  'Eagle',
  'Hawk',
  'Raven',
  'Sparrow',
  'Robin',
  'Heron',
  'Crane',
  'Swan',
  'Dolphin',
  'Whale',
  'Seal',
  'Panther',
  'Leopard',
  'Cheetah',
  'Jaguar',
  'Lynx',
  'Bobcat',
  'Badger',
  'Beaver',
  'Bear',
  'Moose',
  'Elk',
  'Deer',
  'Rabbit',
  'Hare',
  'Squirrel',
  'Hedgehog',
  'Raccoon',
  'Koala',
  'Kangaroo',
  'Platypus',
  'Armadillo',
  'Meerkat',
  'Mongoose',
  'Ferret',
  'Weasel',
  'Antelope',
  'Gazelle',
  'Bison',
  'Buffalo',
  'Camel',
  'Llama',
  'Alpaca',
  'Zebra',
  'Giraffe',
  'Rhino',
  'Hippo',
  'Toucan',
  'Parrot',
  'Flamingo',
  'Pelican',
  'Penguin',
]);
